# Generated by Django 6.0.4 on 2026-05-02 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.CharField(default='daily', max_length=20)),
                ('platforms', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('themes', models.JSONField(blank=True, default=list)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=40)),
                ('sort_order', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=10)),
                ('day_of_week', models.CharField(blank=True, default='', max_length=10)),
                ('occasion', models.CharField(blank=True, default='', max_length=100)),
                ('post_type', models.CharField(blank=True, default='', max_length=20)),
                ('platforms', models.JSONField(default=list)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.TextField(blank=True, default='')),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('call_to_action', models.CharField(blank=True, default='', max_length=500)),
                ('image_prompt', models.TextField(blank=True, default='')),
                ('image_aspect_ratio', models.CharField(default='1:1', max_length=10)),
                ('color_palette_hint', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('image_status', models.CharField(default='pending', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hub.generatedplan')),
            ],
        ),
    ]
