# Generated by Django 6.0.4 on 2026-05-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_generatedplan_admin_note_generatedplan_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='platform_counts',
            field=models.JSONField(default=dict),
        ),
    ]
