# Generated by Django 6.0.4 on 2026-05-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_planrequest_platform_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorequest',
            name='platform_counts',
            field=models.JSONField(default=dict),
        ),
    ]
