# Generated by Django 6.0.4 on 2026-05-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_videorequest_platform_counts'),
        ('video', '0002_generatedvideoplan_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorequest',
            name='generated_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_request', to='video.generatedvideoplan'),
        ),
    ]
