# Generated by Django 6.0.4 on 2026-05-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_videorequest_generated_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorequest',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
