# Generated by Django 6.0.4 on 2026-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_videorequest_duration_videorequest_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='buffer_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='buffer_channels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
