# Generated by Django 6.0.4 on 2026-05-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_businessprofile_buffer_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='buffer_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='buffer_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='buffer_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
