# Generated by Django 6.0.4 on 2026-05-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_businessprofile_buffer_refresh_token_and_more'),
        ('video', '0002_generatedvideoplan_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='video_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='video.generatedvideopost'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='hub.generatedpost'),
        ),
    ]
