# Generated by Django 6.0.4 on 2026-05-04 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedVideoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.CharField(default='daily', max_length=20)),
                ('platforms', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('themes', models.JSONField(blank=True, default=list)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_video_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=10)),
                ('day_of_week', models.CharField(blank=True, default='', max_length=10)),
                ('occasion', models.CharField(blank=True, default='', max_length=100)),
                ('post_type', models.CharField(blank=True, default='', max_length=30)),
                ('platforms', models.JSONField(default=list)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('script', models.TextField(blank=True, default='')),
                ('caption', models.TextField(blank=True, default='')),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('call_to_action', models.CharField(blank=True, default='', max_length=500)),
                ('video_prompt', models.TextField(blank=True, default='')),
                ('aspect_ratio', models.CharField(default='9:16', max_length=10)),
                ('duration', models.CharField(default='5', max_length=10)),
                ('color_palette_hint', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, default='', max_length=1000)),
                ('video_status', models.CharField(default='pending', max_length=20)),
                ('generation_task_id', models.CharField(blank=True, default='', max_length=150)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_posts', to='video.generatedvideoplan')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='', max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('target_platforms', models.JSONField(blank=True, default=list)),
                ('target_audience', models.TextField(blank=True, default='')),
                ('goals', models.TextField(blank=True, default='')),
                ('video_style', models.CharField(blank=True, default='', max_length=100)),
                ('tone', models.CharField(blank=True, default='', max_length=100)),
                ('duration_pref', models.CharField(blank=True, default='5', max_length=50)),
                ('music_preference', models.CharField(blank=True, default='none', max_length=100)),
                ('voiceover', models.BooleanField(default=False)),
                ('brand_colors', models.JSONField(blank=True, default=list)),
                ('logo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('fonts', models.CharField(blank=True, default='', max_length=255)),
                ('instagram', models.CharField(blank=True, default='', max_length=255)),
                ('youtube', models.CharField(blank=True, default='', max_length=255)),
                ('tiktok', models.CharField(blank=True, default='', max_length=255)),
                ('facebook', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
