# Generated by Django 6.0.4 on 2026-05-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvideoplan',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generatedvideoplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedvideoplan',
            name='status',
            field=models.CharField(default='approved', max_length=20),
        ),
    ]
